### ISSUE TITLE
<data> Label processing error

### ISSUE THREAD

**Issue by Davider-code** [msftrncs/PwshReadXmlPList#4]
thanks for the powershell tools!

I found a problem in using,  **< data > label processing error,** 

For example:
______________________________________________________________________________________
1.
before:
```xml
<data>U0FUMA==</data>
```
after:
```xml
<string>83 65 84 48</string>
```
____________________________________________________________
2.
before:
```xml
				<key>Find</key>
				<data>RXh0ZXJuYWw=</data>
```
after:
```xml
				<key>Find</key>
				<array>
					<integer>69</integer>
					<integer>120</integer>
					<integer>116</integer>
					<integer>101</integer>
					<integer>114</integer>
					<integer>110</integer>
					<integer>97</integer>
					<integer>108</integer>
				</array>
```
______________________________________________________________________________________

My programming level, English expression is not very good, 

so, I recorded a video demonstration: https://www12.zippyshare.com/v/CKLQBgMj/file.html

Related documents:  https://www12.zippyshare.com/v/4VdpVBR0/file.html

This is a good tool. Thank you in advance

**Comment by msftrncs** [comment]
Hi.  sorry for the delay in response.

Thanks for bringing this up.  It is looking like the issue is that `ConvertFrom-Plist` is resulting in the `<DATA>` tags being stored in `[Object[]]` instead of `[Byte[]]`.   I am guessing this occurred when I switched to using a `class` instead of a `function`, the class method has to have a return type.  The type `[Object]` can hold any return, but it obscures the real type.

This is causing ConvertTo-Plist to have a different result when converting the document back to PList.

It looks like the fix is pretty simple.  A well placed `,` (comma) seems to be the ticket.  I probably overlooked this at the time, due to not having many examples using `<DATA>`

I'll get a fix PR up.
